auth_enabled: ${LOKI_AUTH_ENABLED}

analytics:
  reporting_enabled: ${LOKI_ANALYTICS_REPORTING_ENABLED}

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: ${LOKI_SERVER_LOG_LEVEL}

common:
  path_prefix: /loki
  compactor_address: http://loki-write:3100
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

memberlist:
  join_members: ${LOKI_MEMBERLIST_JOIN_MEMBERS}
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1m
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1m
  chunk_retain_period: 30s
  chunk_encoding: snappy
  chunk_target_size: 1.572864e+06
  chunk_block_size: 262144
  flush_op_timeout: 10s

ruler:
  enable_api: true
  wal:
    dir: /tmp/ruler-wal
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /tmp/prom-rules
  alertmanager_url: http://alertmanager:9093
  external_url: ${LOKI_RULER_EXTERNAL_URL}

query_scheduler:
  max_outstanding_requests_per_tenant: ${LOKI_QUERY_SCHEDULER_MAX_OUTSTANDING_REQUESTS_PER_TENANT}

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_enabled: true

limits_config:
  retention_period: ${LOKI_LIMITS_CONFIG_RETENTION_PERIOD}
  query_timeout: 5m
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  split_queries_by_interval: 15m


chunk_store_config:
  max_look_back_period: 336h
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 50
      ttl: 1h

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h

query_range:
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 2048

querier:
  query_ingesters_within: 2h
