auth_enabled: ${LOKI_AUTH_ENABLED}

analytics:
  reporting_enabled: ${LOKI_ANALYTICS_REPORTING_ENABLED}

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: ${LOKI_SERVER_LOG_LEVEL}

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

frontend:
  max_outstanding_per_tenant: ${LOKI_FRONTEND_MAX_OUTSTANDING_PER_TENANT}
