version: '3.9'

x-loki-deploy-prod: &loki-deploy-prod
  placement:
    constraints:
      - node.role == worker

services:
  loki-read:
    deploy:
      << : *loki-deploy-prod

  loki-write:
    deploy:
      << : *loki-deploy-prod

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: ${VOL_BACKING}
      perfmode: ${VOL_PERFMODE}
