version: '3.9'

services:
  loki:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: ${VOL_BACKING}
      perfmode: ${VOL_PERFMODE}
